import os
from fastapi import FastAPI, HTTPException
from fastapi.responses import JSONResponse
from fastapi.middleware.cors import CORSMiddleware
import httpx
from dotenv import load_dotenv

load_dotenv()

GATEWAY_URL = os.getenv("GATEWAY_URL", "http://localhost:8000")
API_KEY = os.getenv("API_KEY", "test-api-key")
USER_ID = os.getenv("USER_ID", "test-user-id")

app = FastAPI(title="Auth Broker", version="1.0.0")

# Add CORS middleware to allow browser requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
async def root():
    """Root endpoint for health check"""
    return {"status": "Auth Broker Running"}


@app.get("/health")
async def health():
    """Health check endpoint"""
    return {"status": "ok"}


@app.post("/request-token")
async def request_token():
    """
    Fetch access token from gateway using hardcoded API key.
    Returns the token response from gateway.
    """
    try:
        async with httpx.AsyncClient() as client:
            print(f"Using API_KEY: {API_KEY[:5]}...{API_KEY[-5:] if len(API_KEY) > 10 else ''}")
            
            # The gateway authenticates API keys via Authorization header
            # and expects a JSON body with user_id for the token endpoint
            response = await client.post(
                f"{GATEWAY_URL}/api/v1/auth/token",
                headers={"Authorization": f"{API_KEY}"},
                json={"user_id": USER_ID}
            )

            if response.status_code != 200:
                print(f"Gateway error {response.status_code}: {response.text}")
                return JSONResponse(
                    status_code=response.status_code,
                    content={
                        "error": "Failed to get token from gateway", 
                        "detail": response.json() if "application/json" in response.headers.get("Content-Type", "") else response.text
                    }
                )
            
            token_data = response.json()
            print('New access token generated by broker')
            return token_data
    
    except Exception as e:
        print(f"Broker Exception: {str(e)}")
        return JSONResponse(
            status_code=500,
            content={"error": "Internal server error", "detail": str(e)}
        )


def main():
    """Entry point for Hatch script"""
    import uvicorn
    import argparse
    
    parser = argparse.ArgumentParser()
    parser.add_argument("-r", "--reload", action="store_true", help="Enable auto-reload")
    args, _ = parser.parse_known_args()
    
    port = int(os.getenv("PORT", 8001))
    
    if args.reload:
        uvicorn.run("main:app", host="0.0.0.0", port=port, reload=True)
    else:
        uvicorn.run(app, host="0.0.0.0", port=port)


if __name__ == "__main__":
    main()
